// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: accounts.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO user_accounts (user_id)
VALUES ($1)
RETURNING account_id, user_id, balance, created_at, updated_at
`

func (q *Queries) CreateAccount(ctx context.Context, userID pgtype.UUID) (UserAccount, error) {
	row := q.db.QueryRow(ctx, createAccount, userID)
	var i UserAccount
	err := row.Scan(
		&i.AccountID,
		&i.UserID,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const decrementBalance = `-- name: DecrementBalance :one
UPDATE user_accounts
SET balance = balance - $1, updated_at = NOW()
WHERE user_id = $2
RETURNING account_id, user_id, balance, created_at, updated_at
`

type DecrementBalanceParams struct {
	Balance pgtype.Numeric `json:"balance"`
	UserID  pgtype.UUID    `json:"user_id"`
}

func (q *Queries) DecrementBalance(ctx context.Context, arg DecrementBalanceParams) (UserAccount, error) {
	row := q.db.QueryRow(ctx, decrementBalance, arg.Balance, arg.UserID)
	var i UserAccount
	err := row.Scan(
		&i.AccountID,
		&i.UserID,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountByUserID = `-- name: GetAccountByUserID :one
SELECT account_id, user_id, balance, created_at, updated_at FROM user_accounts
WHERE user_id = $1
`

func (q *Queries) GetAccountByUserID(ctx context.Context, userID pgtype.UUID) (UserAccount, error) {
	row := q.db.QueryRow(ctx, getAccountByUserID, userID)
	var i UserAccount
	err := row.Scan(
		&i.AccountID,
		&i.UserID,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementBalance = `-- name: IncrementBalance :one
UPDATE user_accounts
SET balance = balance + $1, updated_at = NOW()
WHERE user_id = $2
RETURNING account_id, user_id, balance, created_at, updated_at
`

type IncrementBalanceParams struct {
	Balance pgtype.Numeric `json:"balance"`
	UserID  pgtype.UUID    `json:"user_id"`
}

func (q *Queries) IncrementBalance(ctx context.Context, arg IncrementBalanceParams) (UserAccount, error) {
	row := q.db.QueryRow(ctx, incrementBalance, arg.Balance, arg.UserID)
	var i UserAccount
	err := row.Scan(
		&i.AccountID,
		&i.UserID,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
