// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Transaction struct {
	ID        int32            `json:"id"`
	Amount    pgtype.Numeric   `json:"amount"`
	Reason    *string          `json:"reason"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	Type      *string          `json:"type"`
	UserID    pgtype.UUID      `json:"user_id"`
}

type User struct {
	ID        pgtype.UUID        `json:"id"`
	Username  string             `json:"username"`
	Email     string             `json:"email"`
	Password  string             `json:"password"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
