// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transactions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (amount, reason, type, user_id) 
VALUES ($1, $2, $3, $4)
 RETURNING id, amount, reason, created_at, type, user_id
`

type CreateTransactionParams struct {
	Amount pgtype.Numeric `json:"amount"`
	Reason *string        `json:"reason"`
	Type   *string        `json:"type"`
	UserID pgtype.UUID    `json:"user_id"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.Amount,
		arg.Reason,
		arg.Type,
		arg.UserID,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Amount,
		&i.Reason,
		&i.CreatedAt,
		&i.Type,
		&i.UserID,
	)
	return i, err
}

const getTransactions = `-- name: GetTransactions :many
SELECT id, amount, reason, created_at, type, user_id FROM transactions
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetTransactions(ctx context.Context, userID pgtype.UUID) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, getTransactions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.Amount,
			&i.Reason,
			&i.CreatedAt,
			&i.Type,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
